config/routes.rb
Rails.application.routes.draw do
  root 'events#index' 
  
  devise_for :user
  
  resources :events do 
    collection do 
      get :my
    end
  end
  
  namespace :api do
    resources :events
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string
#  start       :datetime
#  description :text
#  repeat      :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Event < ApplicationRecord
  class << self
    def by_period(events, start, stop)
      steps = {"day" => 1.day, "week" => 1.week, "month" => 1.month, "year" => 1.year}
      phantom_events = []
      cur_time = start
      stop_time = (stop).to_time
      event = events
      event.each do |e|
        curn_time = (cur_time).to_time
        if e.repeat != ""
          step = steps[e.repeat]
          start_time_event = e.start
          while (curn_time <= stop_time)  do      
            phantom_events << e.attributes.merge("start" => start_time_event)
            start_time_event = start_time_event + step
            curn_time = start_time_event
          end
        else
          phantom_events << e.attributes
        end
        phantom_events = phantom_events.select { |e| e["start"] >= start }
      end

      return phantom_events
    end
    def all_events(start, stop)
      test_events = Event.where("start <= ?", stop)    
      by_period(test_events, start, stop)
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  full_name              :string
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  respond_to :json
  def index 	
  end
  
  def show   
    events = Event.all_events(params[:start], params[:end])
    events = events.map do |e| 
      curl = {"url" => (event_path(e["id"]))}
      e.merge(curl)
    end
    render json: events
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index 
  end

  def show
    @acces_user
    @event = Event.find(params[:id])  
    if  @event.user_id == current_user.id
      @acces_user = true
    else
      @acces_user = false
    end
  end

  def new
    @event = Event.new
    @current_user = current_user.id
    @dont_repeat = nil
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
      else
        format.html { render :action => "edit" }      
      end
    end    
  end

  def create
    @current_user = current_user.id
    @current_user = {"user_id" => (@current_user)}
    event_params_save = (event_params).merge(@current_user)
    @event = Event.new(event_params_save)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, :notice => 'Event was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.delete
    redirect_to events_url
  end

  def my
    @events = Event.where("user_id = ?", current_user.id)
  end

  private

  def event_params
    params.require(:event).permit(:id, :title, :start, :description, :repeat)
  end   
end     

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_allevents.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Starts at:</b>
  <%= @event.start %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Repeat:</b>
  <%= @event.repeat %>
</p>

<%= link_to 'Back', events_path, class: 'btn btn-primary' %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
<% if @event.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

  <ul>
    <% @event.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>
<br>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</div>
<br>
<div class="field">
  <%= f.label :start %><br />
  <%= f.datetime_select :start %>
</div>
<div class="field">
  <%= f.label :dont_repeat %>
  <%= f.radio_button(:repeat, "")  %>
</div>
<div class="field">
  <%= f.label :repeat_everyday %>
  <%= f.radio_button(:repeat, "day") %>
</div>
<div class="field">
  <%= f.label :repeat_everyweek %>
  <%= f.radio_button(:repeat, "week") %>
</div>  
<div class="field">
  <%= f.label :repeat_everymonth %>
  <%= f.radio_button(:repeat, "month") %>
</div>
<div class="field">
  <%= f.label :repeat_everyyear %>
  <%= f.radio_button(:repeat, "year") %>
</div>
  <%= f.submit "OK", class: 'btn btn-primary' %>
  <%= link_to 'Back', events_path, class: 'btn btn-primary' %>
<% end %>

app/views/events/_myevents.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Title:</b>
	<%= @event.title %>
</p>

<p>
	<b>Starts at:</b>
	<%= @event.start %>
</p>

<p>
	<b>Description:</b>
	<%= @event.description %>
</p>

<p>
	<b>Repeat:</b>
	<%= @event.repeat %>
</p>

<%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-primary' %>
<%= link_to 'Delete', event_path, :method => :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-primary' %>
<%= link_to 'Back', events_path, class: 'btn btn-primary' %>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p class="text-info"><%= current_user.email %></p>
<div class='form-inline'>
  <%= link_to "My events", my_events_path, class: 'btn btn-primary' %>
  <%= link_to "New event", new_event_path, class: 'btn btn-primary' %>
  <%= link_to "log out", destroy_user_session_path, :method => :delete, class: 'btn btn-primary' %>
  <%= link_to "Edit profile", edit_user_registration_path, class: 'btn btn-primary' %>
</div>
<br>
<div id='calendar'>
 <%= javascript_tag do %>
 $(document).ready(function() 
 {
 $('#calendar').fullCalendar(
 {
 events: '/api/events/index',
 header: {
 left: 'prev,next today',
 center: 'title',
 right: 'month,basicWeek,basicDay'
},
navLinks: true			
});
});
<%  end %>
</div>

app/views/events/my.html.erb
<h1>My events</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Type of repeat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |e| %>
      <tr>
        <td><%= e.title %></td>
        <td><%= e.description %></td>
        <td><%= e.start %></td>
        <td><%= e.repeat %></td>
        <td><%= link_to 'Show', event_path(e.id), class: 'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', root_path, class: 'btn btn-primary' %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

app/views/events/preview.html.erb
<h1>My events</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Type of repeat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |e| %>
      <tr>
        <td><%= e.title %></td>
        <td><%= e.description %></td>
        <td><%= e.start %></td>
        <td><%= e.repeat %></td>
        <td><%= link_to 'Show', event_path(e.id), class: 'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', root_path, class: 'btn btn-primary' %>

app/views/events/show.html.erb
<h1>Event</h1>
<% if @acces_user == true %>
<%= render 'myevents' %>
<% else %>
<%= render 'allevents' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>  
  <div class="container">
   <%= yield %>
  </div>
</body>
</html>